const countriesAndCapitals = [
    { country: "Afghanistan", capital: "Kabul" },
    { country: "Albanien", capital: "Tirana" },
    { country: "Algeriet", capital: "Algiers" },
    { country: "Andorra", capital: "Andorra la Vella" },
    { country: "Angola", capital: "Luanda" },
    { country: "Antigua og Barbuda", capital: "Saint John's" },
    { country: "Argentina", capital: "Buenos Aires" },
    { country: "Armenien", capital: "Jerevan" },
    { country: "Australien", capital: "Canberra" },
    { country: "Østrig", capital: "Wien" },
    { country: "Aserbajdsjan", capital: "Baku" },
    { country: "Bahamas", capital: "Nassau" },
    { country: "Bahrain", capital: "Manama" },
    { country: "Bangladesh", capital: "Dhaka" },
    { country: "Barbados", capital: "Bridgetown" },
    { country: "Hviderusland", capital: "Minsk" },
    { country: "Belgien", capital: "Bruxelles" },
    { country: "Belize", capital: "Belmopan" },
    { country: "Benin", capital: "Porto-Novo" },
    { country: "Bhutan", capital: "Thimphu" },
    { country: "Bolivia", capital: "Sucre" },
    { country: "Bosnien-Hercegovina", capital: "Sarajevo" },
    { country: "Botswana", capital: "Gaborone" },
    { country: "Brasilien", capital: "Brasília" },
    { country: "Brunei", capital: "Bandar Seri Begawan" },
    { country: "Bulgarien", capital: "Sofia" },
    { country: "Burkina Faso", capital: "Ouagadougou" },
    { country: "Burundi", capital: "Gitega" },
    { country: "Cambodja", capital: "Phnom Penh" },
    { country: "Cameroun", capital: "Yaoundé" },
    { country: "Canada", capital: "Ottawa" },
    { country: "Centralafrikanske Republik", capital: "Bangui" },
    { country: "Tchad", capital: "N'Djamena" },
    { country: "Chile", capital: "Santiago" },
    { country: "Kina", capital: "Beijing" },
    { country: "Colombia", capital: "Bogotá" },
    { country: "Comorerne", capital: "Moroni" },
    { country: "Congo (DR Congo)", capital: "Kinshasa" },
    { country: "Congo (Republikken Congo)", capital: "Brazzaville" },
    { country: "Costa Rica", capital: "San José" },
    { country: "Kroatien", capital: "Zagreb" },
    { country: "Cuba", capital: "Havana" },
    { country: "Cypern", capital: "Nicosia" },
    { country: "Tjekkiet", capital: "Prag" },
    { country: "Danmark", capital: "København" },
    { country: "Djibouti", capital: "Djibouti" },
    { country: "Dominica", capital: "Roseau" },
    { country: "Den Dominikanske Republik", capital: "Santo Domingo" },
    { country: "Ecuador", capital: "Quito" },
    { country: "Egypten", capital: "Kairo" },
    { country: "El Salvador", capital: "San Salvador" },
    { country: "Ækvatorialguinea", capital: "Malabo" },
    { country: "Eritrea", capital: "Asmara" },
    { country: "Estland", capital: "Tallinn" },
    { country: "Eswatini", capital: "Mbabane" },
    { country: "Etiopien", capital: "Addis Abeba" },
    { country: "Fiji", capital: "Suva" },
    { country: "Finland", capital: "Helsinki" },
    { country: "Frankrig", capital: "Paris" },
    { country: "Gabon", capital: "Libreville" },
    { country: "Gambia", capital: "Banjul" },
    { country: "Georgien", capital: "Tbilisi" },
    { country: "Tyskland", capital: "Berlin" },
    { country: "Ghana", capital: "Accra" },
    { country: "Grækenland", capital: "Athen" },
    { country: "Grenada", capital: "St. George's" },
    { country: "Guatemala", capital: "Guatemala City" },
    { country: "Guinea", capital: "Conakry" },
    { country: "Guinea-Bissau", capital: "Bissau" },
    { country: "Guyana", capital: "Georgetown" },
    { country: "Haiti", capital: "Port-au-Prince" },
    { country: "Honduras", capital: "Tegucigalpa" },
    { country: "Ungarn", capital: "Budapest" },
    { country: "Island", capital: "Reykjavik" },
    { country: "Indien", capital: "New Delhi" },
    { country: "Indonesien", capital: "Jakarta" },
    { country: "Iran", capital: "Teheran" },
    { country: "Irak", capital: "Bagdad" },
    { country: "Irland", capital: "Dublin" },
    { country: "Israel", capital: "Jerusalem" },
    { country: "Italien", capital: "Rom" },
    { country: "Jamaica", capital: "Kingston" },
    { country: "Japan", capital: "Tokyo" },
    { country: "Jordan", capital: "Amman" },
    { country: "Kasakhstan", capital: "Astana" },
    { country: "Kenya", capital: "Nairobi" },
    { country: "Kiribati", capital: "Tarawa" },
    { country: "Nordkorea", capital: "Pyongyang" },
    { country: "Sydkorea", capital: "Seoul" },
    { country: "Kosovo", capital: "Pristina" },
    { country: "Kuwait", capital: "Kuwait City" },
    { country: "Kirgisistan", capital: "Bisjkek" },
    { country: "Laos", capital: "Vientiane" },
    { country: "Letland", capital: "Riga" },
    { country: "Libanon", capital: "Beirut" },
    { country: "Lesotho", capital: "Maseru" },
    { country: "Liberia", capital: "Monrovia" },
    { country: "Libyen", capital: "Tripoli" },
    { country: "Liechtenstein", capital: "Vaduz" },
    { country: "Litauen", capital: "Vilnius" },
    { country: "Luxembourg", capital: "Luxembourg City" },
    { country: "Madagaskar", capital: "Antananarivo" },
    { country: "Malawi", capital: "Lilongwe" },
    { country: "Malaysia", capital: "Kuala Lumpur" },
    { country: "Maldiverne", capital: "Malé" },
    { country: "Mali", capital: "Bamako" },
    { country: "Malta", capital: "Valletta" },
    { country: "Marshalløerne", capital: "Majuro" },
    { country: "Mauretanien", capital: "Nouakchott" },
    { country: "Mauritius", capital: "Port Louis" },
    { country: "Mexico", capital: "Mexico City" },
    { country: "Mikronesien", capital: "Palikir" },
    { country: "Moldova", capital: "Chisinau" },
    { country: "Monaco", capital: "Monaco" },
    { country: "Mongoliet", capital: "Ulaanbaatar" },
    { country: "Montenegro", capital: "Podgorica" },
    { country: "Marokko", capital: "Rabat" },
    { country: "Mozambique", capital: "Maputo" },
    { country: "Myanmar", capital: "Naypyidaw" },
    { country: "Namibia", capital: "Windhoek" },
    { country: "Nauru", capital: "Yaren" },
    { country: "Nepal", capital: "Katmandu" },
    { country: "Holland", capital: "Amsterdam" },
    { country: "New Zealand", capital: "Wellington" },
    { country: "Nicaragua", capital: "Managua" },
    { country: "Niger", capital: "Niamey" },
    { country: "Nigeria", capital: "Abuja" },
    { country: "Nordmakedonien", capital: "Skopje" },
    { country: "Norge", capital: "Oslo" },
    { country: "Oman", capital: "Muskat" },
    { country: "Pakistan", capital: "Islamabad" },
    { country: "Palau", capital: "Ngerulmud" },
    { country: "Palæstina", capital: "Ramallah" },
    { country: "Panama", capital: "Panama City" },
    { country: "Papua Ny Guinea", capital: "Port Moresby" },
    { country: "Paraguay", capital: "Asuncion" },
    { country: "Peru", capital: "Lima" },
    { country: "Filippinerne", capital: "Manila" },
    { country: "Polen", capital: "Warszawa" },
    { country: "Portugal", capital: "Lissabon" },
    { country: "Qatar", capital: "Doha" },
    { country: "Rumænien", capital: "Bukarest" },
    { country: "Rusland", capital: "Moskva" },
    { country: "Rwanda", capital: "Kigali" },
    { country: "Saint Kitts og Nevis", capital: "Basseterre" },
    { country: "Saint Lucia", capital: "Castries" },
    { country: "Saint Vincent og Grenadinerne", capital: "Kingstown" },
    { country: "Samoa", capital: "Apia" },
    { country: "San Marino", capital: "San Marino" },
    { country: "Sao Tome og Principe", capital: "Sao Tome" },
    { country: "Saudi-Arabien", capital: "Riyadh" },
    { country: "Senegal", capital: "Dakar" },
    { country: "Serbien", capital: "Beograd" },
    { country: "Seychellerne", capital: "Victoria" },
    { country: "Sierra Leone", capital: "Freetown" },
    { country: "Singapore", capital: "Singapore" },
    { country: "Slovakiet", capital: "Bratislava" },
    { country: "Slovenien", capital: "Ljubljana" },
    { country: "Salomonøerne", capital: "Honiara" },
    { country: "Somalia", capital: "Mogadishu" },
    { country: "Sydafrika", capital: "Pretoria" },
    { country: "Sydsudan", capital: "Juba" },
    { country: "Spanien", capital: "Madrid" },
    { country: "Sri Lanka", capital: "Sri Jayawardenapura Kotte" },
    { country: "Sudan", capital: "Khartoum" },
    { country: "Surinam", capital: "Paramaribo" },
    { country: "Sverige", capital: "Stockholm" },
    { country: "Schweiz", capital: "Bern" },
    { country: "Syrien", capital: "Damaskus" },
    { country: "Tajikistan", capital: "Dusjanbe" },
    { country: "Tanzania", capital: "Dodoma" },
    { country: "Thailand", capital: "Bangkok" },
    { country: "Togo", capital: "Lomé" },
    { country: "Tonga", capital: "Nuku'alofa" },
    { country: "Trinidad og Tobago", capital: "Port of Spain" },
    { country: "Tunesien", capital: "Tunis" },
    { country: "Turkmenistan", capital: "Ashgabat" },
    { country: "Tuvalu", capital: "Funafuti" },
    { country: "Uganda", capital: "Kampala" },
    { country: "Ukraine", capital: "Kyiv" },
    { country: "Forenede Arabiske Emirater", capital: "Abu Dhabi" },
    { country: "Storbritannien", capital: "London" },
    { country: "USA", capital: "Washington D.C." },
    { country: "Uruguay", capital: "Montevideo" },
    { country: "Usbekistan", capital: "Tashkent" },
    { country: "Vanuatu", capital: "Port Vila" },
    { country: "Vatikanstaten", capital: "Vatikanstaten" },
    { country: "Venezuela", capital: "Caracas" },
    { country: "Vietnam", capital: "Hanoi" },
    { country: "Yemen", capital: "Sanaa" },
    { country: "Zambia", capital: "Lusaka" },
    { country: "Zimbabwe", capital: "Harare" }
];

// Referencer til HTML-elementer
const randomCountryButton = document.getElementById("randomCountry");
const showCapitalButton = document.getElementById("showCapital");
const countryDisplay = document.getElementById("country");
const capitalDisplay = document.getElementById("capital");

let selectedCountry = null;

// Funktion til at vælge et tilfældigt land
function chooseRandomCountry() {
    const randomIndex = Math.floor(Math.random() * countriesAndCapitals.length);
    selectedCountry = countriesAndCapitals[randomIndex];
    countryDisplay.textContent = `Land: ${selectedCountry.country}`;
    capitalDisplay.textContent = ""; // Nulstil tidligere hovedstad
    showCapitalButton.disabled = false; // Aktiver "Vis hovedstad"-knappen
}

// Funktion til at vise hovedstaden
function showCapital() {
    if (selectedCountry) {
        capitalDisplay.textContent = `Hovedstad: ${selectedCountry.capital}`;
    }
}

// Event listeners
randomCountryButton.addEventListener("click", chooseRandomCountry);
showCapitalButton.addEventListener("click", showCapital);
